// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth2FA(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DelData(arg1:number):Promise<boolean>;

export function GetData():Promise<string>;

export function Loggin(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<boolean>;

export function Manage2FA(arg1:boolean):Promise<string>;

export function ModData(arg1:string,arg2:number):Promise<boolean>;

export function Register(arg1:string,arg2:string,arg3:number):Promise<string>;

export function UpdateData(arg1:string):Promise<boolean>;
