// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData() {
  return window['go']['main']['App']['GetData']();
}

export function Loggin(arg1, arg2) {
  return window['go']['main']['App']['Loggin'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function UpdateData(arg1) {
  return window['go']['main']['App']['UpdateData'](arg1);
}
