// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth2FA(arg1, arg2, arg3) {
  return window['go']['main']['App']['Auth2FA'](arg1, arg2, arg3);
}

export function DelData(arg1) {
  return window['go']['main']['App']['DelData'](arg1);
}

export function GetData() {
  return window['go']['main']['App']['GetData']();
}

export function Loggin(arg1, arg2) {
  return window['go']['main']['App']['Loggin'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ModData(arg1, arg2) {
  return window['go']['main']['App']['ModData'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function UpdateData(arg1) {
  return window['go']['main']['App']['UpdateData'](arg1);
}
