// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData():Promise<string>;

export function Loggin(arg1:string,arg2:string):Promise<boolean>;

export function Logout():Promise<boolean>;

export function Register(arg1:string,arg2:string):Promise<boolean>;

export function UpdateData(arg1:string):Promise<boolean>;
